### ISSUE TITLE
GitHub Wiki/Readme 작성

### ISSUE THREAD

**Issue by gunooknam** [gunooknam/Assignment2#1]
웹 언어를 Markdown 문법으로 바꿔줄 수 있는 typora에 대한 조사 후 
Typora 를 활용한 Readme + Wiki page 작성

**Comment by gunooknam** [comment]
([Typora]):(https://github.com/gunooknam/Assignment2/wiki/Typora-Study) 에 대한 기능조사에 대한 정보를 Wiki에 생성하였음

**Comment by JooHyungByun** [comment]
GOOD!
