### ISSUE TITLE
파일이 존재하지 않을 경우 예외처리 출력

### ISSUE THREAD

**Issue by gunooknam** [gunooknam/Assignment2#11]
1. text1이나 text2 둘 중 하나가 없는 경우

2. text1, text2 모두 없는 경우

**Comment by gulike7** [comment]
errorcheck 함수의 반환형을 int로 해서 반환값이 0이면 이상없음, -1이면 에러로 하여 함수를 호출하는것으로 에러여부를 알 수 있게 가능할까요?

**Comment by gulike7** [comment]
오오 되게좋내요

**Comment by JooHyungByun** [comment]
확인했습니다~~ 굿
