### ISSUE TITLE
팀원 한명 드랍으로 인한 README 수정

### ISSUE THREAD

**Issue by gunooknam** [gunooknam/Assignment2#13]
추가 역할 분배 필요

**Comment by gulike7** [comment]
추가적으로 해야할 역활이 무엇인가요?

**Comment by JooHyungByun** [comment]
파일시간 받아오기 함수가 비게되는데 제가 진행하던 수정 날짜/시간을 받아오기 위해 필요한 부분으로 제가 진행하겠습니다.
