### ISSUE TITLE
filestat1함수 주석부분 수정 요청

### ISSUE THREAD

**Issue by JooHyungByun** [gunooknam/Assignment2#42]
void filestat1(void)
{
	if(stat("text1", &stat1)){
		errno=errno<<1;
	}
	/*
	else{ //테스트를 위한 코드
		printf("size : %d \n", (int)stat1.st_size);
		printf("size : %d \n", (int)stat1.st_block);
	}
	*/ 
}

주석처리된 else부분은 테스트를 하려고 만드신건가요??
테스트는 그냥 테스트브랜치 따로 만들어서 진행하면 될꺼같은데 지워도 될까요

**Comment by gunooknam** [comment]
통일성을 위해서 지우는게 나은듯

**Comment by JooHyungByun** [comment]
지웠습니다 close하겠습니다

**Comment by gulike7** [comment]
네
